server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: sensor-data-processor
  web:
    resources:
      add-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rest-consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: HikariSensorPool
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  security:
    user:
      name: admin
      password: password

springdoc:
  swagger-ui:
    path: /swagger-ui.html

simulator:
  enabled: true
  fixed-rate-ms: 2000
  max-records: 100
  allow-spikes: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus