apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-deployment
  labels:
    app: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot
  template:
    metadata:
      labels:
        app: iot
    spec:
      containers:
        - name: iot-container
          image: iot-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: iot-service
spec:
  selector:
    app: iot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
