apiVersion: v1
kind: Pod
metadata:
  name: springboot-app
  labels:
    app: springboot
spec:
  containers:
    - name: springboot-container
      image: my-springboot-app
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
